### PR TITLE
Add subpixelPositioning input for popup and marker

### PR DESCRIPTION
**Pull request by marcjulian**
available since maplibre-gl@4.1.0

### CODE REVIEW

**Comment by HarelM** [comment]
I think marker has sub pixel configuration as well in recent version/s.
Can you add it as well?

**Review by HarelM — APPROVED** [review]

**Comment by marcjulian** [comment]
`subpixelPositioning` is available for Marker since [maplibre-gl@4.5.1](https://github.com/maplibre/maplibre-gl-js/releases/tag/v4.5.1). The peerDeps is currently set to v4.1.0, we would need to change that to 4.5.1. Should we do that as well?

**Comment by HarelM** [comment]
Sure

**Review by HarelM — APPROVED** [review]
Nice!

**Pull request merged**
