### PR TITLE
Rename css class

### PR DESCRIPTION
**Pull request by aprilmay**
Proposed fix for #4

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks! Can you change the min version of maplibre dependency as well?

**Comment by aprilmay** [comment]
Thanks to you for this project :)
I updated my branch, it seems that this PR includes this other update. Is that enough?

**Comment by HarelM** [comment]
I think it's also missing here:
https://github.com/maplibre/ngx-maplibre-gl/blob/e217b68324b5fe5ca117b78c5f7b987547d26a3b/projects/ngx-maplibre-gl/package.json#L25

**Comment by aprilmay** [comment]
Right, good catch. Pushed another update.

**Pull request merged**
