### PR TITLE
remove usage of NgZone.onStable and NgZone.onMicrotaskEmpty

### PR DESCRIPTION
**Pull request by marcjulian**
`MapService.setup` is called in afterNextRender

* reference https://angular.dev/guide/experimental/zoneless#remove-ngzoneonmicrotaskempty-ngzoneonunstable-ngzoneisstable-or-ngzoneonstable

### CODE REVIEW

**Comment by marcjulian** [comment]
Yes for now. I will create another PR with additional changes.

**Comment by HarelM** [comment]
Let me know what you want to carve out a new version.
I think we have enough changes to create one.

**Comment by marcjulian** [comment]
Yes you can create a new version! Looks like the map works fine with zoneless (`provideExperimentalZonelessChangeDetection`). 

There might be a bit more work around zoneless for the showcase project, but we can tackle it later.

**Comment by HarelM** [comment]
Great! I'm still far from being zoneless in my app, so it will take time for me to actually test these changes... Nevertheless, this is good!

**Pull request merged**
