### PR TITLE
Feature/terrain

### PR DESCRIPTION
**Pull request by jfollas**
Expose the 3D Terrain functionality from maplibre-gl (first seen in version [v.2.2.0](https://github.com/maplibre/maplibre-gl-js/releases/tag/v2.2.0))

### CODE REVIEW

**Comment by HarelM** [comment]
Thanks for taking the time to add this!
Is this the same terrain source and style that is used in the maplibre examples page? I see some maptiler keys that might problematic...?
Also, can you add a cypress test to cover this page if it's not already covered? Preferably with the new driver pattern which was introduced recently.

**Comment by jfollas** [comment]
> Is this the same terrain source and style that is used in the maplibre examples page? I see some maptiler keys that might problematic...? 

I changed the demos to use sources that are also in use on the maplibre examples page (which includes some maptiler sources).  I also fixed a build bug (modified `public_api.ts`)

> Also, can you add a cypress test to cover this page if it's not already covered? Preferably with the new driver pattern which was introduced recently.

I can't get Cypress to run locally - everything just times out waiting for the browser. Admittedly, it's not something that I have experience with setting up/writing tests for, and could use another contributor's assistance in that regard.

**Comment by HarelM** [comment]
Try running the commands that are written here:
https://github.com/maplibre/ngx-maplibre-gl/blob/65205901d216b983e0519e6f5a1f7495f4e51ee0/.github/workflows/ci.yml#L26
npm run e2e should run this without the browser (at least not in the front).

**Comment by jfollas** [comment]
It was more of an underlying system issue.  I updated my WSL Ubuntu distro to WSL 2, and then the cypress tests started working.  I added the 3 new examples to the runtime-check test

**Comment by jfollas** [comment]
Going to break this up into a revamped Cypress testing PR and then the smaller 3D Terrain PR that will build on that.

**Pull request closed without merging**
