### PR TITLE
regenerate package-lock.json minor lib update

### PR DESCRIPTION
**Pull request by tbo47**
1. I moved `@types/geojson` lib in the devDependencies section of `package.json` 
2. I regenerate `package-lock.json` and made it clear in `package.json` what has changed.  It's minor lib updates.

### CODE REVIEW

**Comment by HarelM** [comment]
I saw that the lock file was changed from version 2 to version 3, can you elaborate on this please?

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Thanks!!

**Comment by HarelM** [comment]
Seems like a bump in ngx-maplibre-gl version was missing so publishing to npm failed 😕
Feel free to open a new PR to update this package.json as well.

**Comment by tbo47** [comment]
> Seems like a bump in ngx-maplibre-gl version was missing so publishing to npm failed 😕 Feel free to open a new PR to update this package.json as well.

I'm curious. Where is it published exactly? I don't see anything here: https://www.npmjs.com/search?q=ngx-maplibre-gl-srcs

**Comment by HarelM** [comment]
https://www.npmjs.com/package/@maplibre/ngx-maplibre-gl

**Pull request merged**
