### PR TITLE
decoupling test (language-switch) from testing framework (cypress)

### PR DESCRIPTION
**Pull request by ShellyDCMS**
Added e2e driver for complete decoupling between test (language-switch) and test framework (cypress), and for test readability.

### CODE REVIEW

**Comment by HarelM** [comment]
Looks great!
Can you remove the unneeded extra click on french button? It's a mistake I did when converting the tests.
If the tests fails it means we need to wait longer for the map to be available...

**Comment by HarelM** [comment]
Seems like the change in ts config broke the ci... :-(

**Comment by ShellyDCMS** [comment]
Restoring tsconfig

**Review by HarelM — APPROVED** [review]

**Comment by ShellyDCMS** [comment]
Can you merge? Or grant me permission to merge?
image

**Pull request merged**
