### PR TITLE
Upgrade to Angular 16

### PR DESCRIPTION
**Pull request by tomLadder**
This upgrades the library to Angular v16

### CODE REVIEW

**Comment by HarelM** [comment]
Did you check that the edit in stack blitz works?

**Comment by HarelM** [comment]
Thanks a lot BTW!

**Comment by HarelM** [comment]
Can you also change the package version to 16 so I'll be able to release this easily after merging this?

**Comment by tomLadder** [comment]
@HarelM Already updated the package version to 16 :)

Tested stackblitz for the simple case "Display a map" which worked fine. All the demos where something was imported from `maplibre-gl` did not work (also happening on the current deployment)

Fixed the issues by adding `@maplibre/maplibre-gl-style-spec` to the stackblitz project dependencies. Also the angular dependencies there where set to fixed major v13. Replaced it to use v16

**Comment by HarelM** [comment]
I think I fixed it to 13 when there was a time it created 12 instead of 13...
The showcase is working in general, if you feel like fixing the stackblitz as well it would be awesome.
This looks good in general.

**Comment by tomLadder** [comment]
@HarelM for example this one is broken: https://maplibre.org/ngx-maplibre-gl/demo/edit/set-style

**Comment by tomLadder** [comment]
Changed it in `package.json` and `projects/ngx-maplibre-gl/package.json` ... or what do you mean?

**Review by HarelM — APPROVED** [review]
THANKS

**Pull request merged**
