### PR TITLE
Upgrade to Angular 15 and MapLibre 3.0

### LINKED ISSUE #89: Angular 15 support
Hi,

Is this support for `Angular 15+`? i.e. I can see Angular 14 only yet. Your thoughts? Thanks!

### PR DESCRIPTION
**Pull request by HarelM**
Resolves #89 by upgrading to maplibre 3.0 and angular 15.0

### CODE REVIEW

**Comment by trytuna** [comment]
Hi @HarelM thank you for pushing the update along. That is very cool to see and motivates me participate in the process in some minor ways.

I've noticed that are is a weird resizing quirk. I was able to reproduce the issue here StackBlitz https://stackblitz.com/edit/angular-bbrhvd

If you open it and try to resize the browser window you get this error multiple times very quickly.

Screenshot 2023-05-24 at 13 17 37

**Comment by HarelM** [comment]
Interesting.
We have noticed some issues with the migration to `ResizeObserver` in maplibre-gl.
We even tried to fix it here #95 and here is the fix:
https://github.com/maplibre/maplibre-gl-js/pull/2552
I'm unable to reproduce what you are seeing with edge or chrome and also the cypress tests which failed with a resize observer error are now passing.
I'm not saying there isn't a bug, I just am unable to see if and better understand what's causing it.
I would recommend opening a different issue and discuss it there.
I believe this version needs to be released, and we can try and fix it for next versions...

**Comment by trytuna** [comment]
I dont know if this helps but I've recorded two short screencasts. Also this are the browser versions that I used:

Chrome Version 113.0.5672.92 (Official Build) (arm64)
Safari Version 16.4 (18615.1.26.11.23)


https://github.com/maplibre/ngx-maplibre-gl/assets/128096/6882d76d-f1a2-4456-aa3f-b1371ba151fa


https://github.com/maplibre/ngx-maplibre-gl/assets/128096/14f42dc5-5f86-4706-866f-2918251115f5

**Comment by trytuna** [comment]
I just found out that setting this style:

```
mgl-map {
  height: 400px;
}
```

Fixes the problem. I have a feeling that many people are going to run into this problem. Its best to address this issue somehow I guess. Unfortunately I don't know much about the inner workings of maplibre to be able to do a PR.

**Comment by HarelM** [comment]
I can see that weird stuff happens there as well.
Can you open a different issue here so we can track it properly?

**Pull request merged**
