### PR TITLE
bump version to 14.0.0-pre.2

### PR DESCRIPTION
**Pull request by BergkampHUN**
changes in #61

### CODE REVIEW

**Comment by BergkampHUN** [comment]
Yes, I've forgotten the lock file, can you show me a commit where I can see where are the other package.json files? I couldn't find it.

**Comment by HarelM** [comment]
https://github.com/maplibre/ngx-maplibre-gl/commit/66a3cc2ee11537303cc8543621d4b32b024dbdbf

**Comment by BergkampHUN** [comment]
Thanks, according to that commit, I found 2 package.json and 2 lock files. I updated them. Please tell me if I missed anything.

**Review by HarelM — APPROVED** [review]

**Comment by HarelM** [comment]
Also, not related to this PR, if you have so time to help me stabilize set-style.cy.ts test it would be very much appreciated :-) I'm having a hard time making it pass reliably... :-(

**Review by HarelM — APPROVED** [review]

**Pull request merged**
