### PR TITLE
fix: remove source based on current id during source update

### LINKED ISSUE #205: Error when updating an existing source
Node: 22.11.0
maplibre-gl: 4.7.1
ngx-maplibre-gl: 18.1.2

When updating the `id` and `tiles` properties of a source component, I get the following error:
```
ERROR Error: There is no source with this ID
    at de.removeSource (maplibre-gl.js:46:124350)
    at t.Map.removeSource (maplibre-gl.js:46:408497)
    at maplibre-ngx-maplibre-gl.mjs:390:30
    at _ZoneDelegate.invoke (zone.js:369:28)
    at ZoneImpl.run (zone.js:111:43)
    at NgZone.runOutsideAngular (core.mjs:7142:28)
    at MapService.removeSource (maplibre-ngx-maplibre-gl.mjs:388:19)
    at SourceDirective.removeSource (maplibre-ngx-maplibre-gl.mjs:947:29)
    at SourceDirective.refresh (maplibre-ngx-maplibre-gl.mjs:942:14)
    at RasterSourceComponent.ngOnChanges (maplibre-ngx-maplibre-gl.mjs:2646:34)
```

I believe I've identified the issue and will provide a PR.

### PR DESCRIPTION
**Pull request by stoneLeaf**
Fixes #205

Current refresh mechanism of the source directive fails when updating the source id.
This is because it bases the removal call on the new id `this.id()` instead of the current one `this.sourceId()`.

### CODE REVIEW

**Comment by stoneLeaf** [comment]
Sure!

**Comment by HarelM** [comment]
I'm not sure I understand why both id and sourceId exists, can you explain? Isn't one of them enough?

**Comment by stoneLeaf** [comment]
@HarelM My understanding of this implementation is that it delegates the full change detection to the source components, which in turns triggers a _refresh_ of the directive (thus needing to store both the old and new value of `id`). I think it's a pretty clean pattern and don't see any obvious refactor which would make it clearer/simpler.

cc @n-elhk

**Comment by HarelM** [comment]
I think my confusion is coming from the fact that sourceId is not marked as private and is a signal instead of a "regular" variable...
In any case, this looks good, thanks!

**Review by HarelM — APPROVED** [review]

**Pull request merged**
